# Generated by Django 4.0.3 on 2022-03-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_posts_body_alter_posts_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=500)),
                ('postId', models.ForeignKey(on_delete=django.db
                                             .models.deletion.PROTECT,
                                             related_name='posts',
                                             to='api.posts')),
            ],
        ),
    ]
