# Generated by Django 4.0.3 on 2022-03-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db
                                             .models.deletion.PROTECT,
                                             related_name='albums',
                                             to='api.posts')),
            ],
        ),
    ]
